import turtle
turtle.shape("turtle")
turtle.speed(3)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.exitonclick()